-- 在 Supabase SQL Editor 中运行以下代码以创建所需的表
CREATE TABLE IF NOT EXISTS ai_insights (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    insight_text text not null
);

-- 开启行级安全 (RLS) 或者关闭，看你的默认设置，如果要公开读写，可以关闭RLS或者添加策略:
-- ALTER TABLE ai_insights DISABLE ROW LEVEL SECURITY;
